### PR TITLE
Create test script for cbr_usd.py module

### PR DESCRIPTION
**Pull request by MadViper**
Asserts moved to the test scripts, Several new asserts added in a process.

### CODE REVIEW

**Comment by epogrebnyak** [comment]
In test_source_url why not just test against a hardcoded string? It is more transparent.

A nice set of tests overall !

**Comment by MadViper** [comment]
Yeah may be your are right, but my intuition told me to chop and reconstruct url.
One benefit can be that this way one can clearly see that arguments are not necessarily fixed.

To my mind, at the end of the day it is matter of preference and I chose this approach.

**Comment by epogrebnyak** [comment]
Maybe you can add one more assert against a string and keep both variants for now?

**Comment by MadViper** [comment]
Yeah maybe I am sorry I do not have time now, Let's discuss it this evening!

**Comment by epogrebnyak** [comment]
I can add later, no problem

23 июн. 2017 г. 9:48 пользователь "MadViper" <notifications@github.com>
написал:

**Pull request merged**
